import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import path from "path";
import { fileURLToPath } from 'url';
import { copyFileSync } from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const currentDir = path.dirname(fileURLToPath(import.meta.url));
const distDir = `${currentDir}/dist`;

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${distDir}/main.js`,
	minify: prod,
};

if (prod) {
	// Production build
	esbuild.build(buildOptions).then(() => {
		copyFileSync(`${currentDir}/manifest.json`, `${distDir}/manifest.json`);
		copyFileSync(`${currentDir}/styles.css`, `${distDir}/styles.css`);
		console.log('✓ Build completed successfully');
	}).catch(() => process.exit(1));
} else {
	// Development build with watch mode
	esbuild.context(buildOptions).then(ctx => {
		ctx.watch();
		copyFileSync(`${currentDir}/manifest.json`, `${distDir}/manifest.json`);
		copyFileSync(`${currentDir}/styles.css`, `${distDir}/styles.css`);
		console.log('👀 Watching for changes...');
	}).catch(() => process.exit(1));
}
